unbind C-b
set -g prefix C-s
bind-key -r C-s send-prefix

bind-key d split-window -h -c '#{pane_current_path}'
bind-key D split-window -v -c '#{pane_current_path}'
bind-key r source-file ~/.tmux.conf \; display-message "config reloaded"

bind-key -n M-Left select-pane -L
bind-key -n M-Down select-pane -D
bind-key -n M-Up select-pane -U
bind-key -n M-Right select-pane -R

set -g default-terminal "screen-256color"

set -g status-left-length 50
set -g status-right " #P "

# Fine adjustment (1 or 2 cursor cells per bump)
bind -n S-Left resize-pane -L 2
bind -n S-Right resize-pane -R 2
bind -n S-Down resize-pane -D 1
bind -n S-Up resize-pane -U 1

# Coarse adjustment (5 or 10 cursor cells per bump)
bind -n C-Left resize-pane -L 10
bind -n C-Right resize-pane -R 10
bind -n C-Down resize-pane -D 5
bind -n C-Up resize-pane -U 5

bind t new-window -c "#{pane_current_path}"
set -g base-index 1
set -g renumber-windows on

bind-key x kill-pane

# Disable escape delay in vim
set -g escape-time 0

set -g mouse on

# Customize status bar
# set -g status-bg white
set-option -g status-style bg=default
set -g status-fg black
set -g status-position top 
